# fly.toml app configuration file generated for ddbot on 2024-12-26T15:24:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ddbot'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  builtin = 'node'

[env]
  PORT = '8080'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1