const { config } = require('dotenv');

module.exports = async (client) => {
  const { GoogleSpreadsheet } = require('google-spreadsheet');
  const { JWT } = require('google-auth-library');

  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
    scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
  });

  client.data = new GoogleSpreadsheet('1JL1pbEePQltqzTDVR-HaT5sKGUK_g7X6PbZmj-LorZw', serviceAccountAuth);
  await client.data.loadInfo();

  client.config = (await client.data.sheetsById[0].getRows())[0];
  client.pools = await client.data.sheetsById[client.config.get("commands")].getRows();
  
}